apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-node4
  labels:
    app: gaia-node4
spec:
  selector:
    matchLabels:
      app: gaia-node4
  replicas: 1
  template:
    metadata:
      labels:
        app: gaia-node4
    spec:
      containers:
        - name: gaia-node4
          image: buryeye7/friday-node:latest
          command: ["./scripts/start-node.sh"]
          env:
            - name: TARGET
              value:  
            - name: WALLET_ALIAS
              value: node4
          ports:
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: network
              containerPort: 26656
              protocol: TCP
            - name: clif
              containerPort: 1317
              protocol: TCP
            - name: prometheus
              containerPort: 26660
              protocol: TCP
      nodeName: ip-172-20-50-65.ap-northeast-1.compute.internal
---
apiVersion: v1
kind: Service
metadata:
  name: gaia-node4
spec:
  type: LoadBalancer
  selector:
    app: gaia-node4
  ports:
    - protocol: TCP
      port: 1317
      targetPort: 1317
